image: python:latest

stages:
  - adjusting
  - test

before_script:
  - apt update -y
  - apt upgrade -y

adjusting:
  stage: adjusting
  script:
    - pip install pycodestyle pydocstyle
    - pycodestyle .
    - pydocstyle .
    
run_test:
  stage: run_test
  script:
    - python -m unittest discover test -v
