image: python:latest

stages:
  - adjusting
  - run_test

before_script:
  - apt update -y
  - apt upgrade -y

adjusting:
  stage: adjusting
  script:
    - pip install pycodestyle pydocstyle
    - pycodestyle . --exclude='test/'
    - pydocstyle . --exclude='test/'
    
run_test:
  stage: run_test
  script:
    - python3 -m unittest discover test -v
